import "./globals.css";
import { ToastContainer } from "react-toastify";


export const metadata = {
  title: "Nodal Circle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ToastContainer position="top-right" />
        {children}
      </body>
    </html>
  );
}
